### ISSUE TITLE
Update this manuscript's thumbnail

### ISSUE THREAD

**Issue by vincerubinetti** [slochower/smirnoff-host-guest-manuscript#61]
Hello Manubot user.

If you were not already aware, your paper is being showcased in the [Manubot Catalog](https://manubot.org/catalog/).

Previously, we were making our own thumbnails for each paper, and hosting them in the same repository as `manubot.org`. But now we are moving to a system of having each paper store its thumbnail in its own repository, and linking to it from there.

Here is our suggested thumbnail for your paper that follows the new [thumbnail guidelines](https://github.com/manubot/catalog#thumbnail-guidelines):

![image](https://user-images.githubusercontent.com/8326331/64820987-a9551880-d57f-11e9-8caa-80814be970ed.png)

OR

![thumbnail](https://user-images.githubusercontent.com/8326331/64820617-c3422b80-d57e-11e9-9f9e-08d4075d974a.png)

Please place this image *in the root of your repository* with the name `thumbnail.png`. Once you have, let us know in this issue and we'll do the rest to update the catalog.

**Comment by slochower** [comment]
Done :)
